name: bank_marketing
version: '1.0.0'
config-version: 2

profile: bank_marketing_profile

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  bank_marketing:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table

