bank_marketing_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "generated-surf-468214-g1"
      dataset: "bank_marketing_dm"
      threads: 4
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      priority: interactive

